# Generated by Django 4.1.1 on 2023-12-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tick', models.PositiveBigIntegerField()),
                ('end_tick', models.PositiveBigIntegerField()),
                ('data', models.JSONField()),
                ('handler', models.CharField(max_length=200)),
            ],
        ),
    ]
