# Generated by Django 4.1.1 on 2023-12-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='handler',
            new_name='handler_id',
        ),
    ]
